### ISSUE TITLE
DS.6 - One app design support

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-sprints#54]
**Epic:** What's the big picture?
Swift team is developing one app and they requested for us to review how they use our design system and help with new components. 

- [x] [New e-bike icon](https://github.com/wmcadigital/wmn-design-system/issues/474)
- [x] [New Out of use station icon](https://github.com/wmcadigital/wmn-design-system/issues/483)
- [x] [App Store screenshots](https://github.com/wmcadigital/wmn-design-system/issues/495)
- [x] [OneApp App Store Beta Icon](https://github.com/wmcadigital/wmn-design-system/issues/505)

 
***
