### ISSUE TITLE
TK3.9 - nTicket product page - Customisations (filters)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#76]
**Epic:** Building an nTicket for my needs

***
#### As a
person finding a multi-operator nTicket

#### I need to
refine my ticket

#### So that
I can build a ticket that meets my needs

***
#### Who is travelling
- [x] User can choose who is travelling
- [x] If user has chosen young person; student; or disabled or older person; show hint that they need a photocard
- [x] User can follow a link to get a photocard
- [x] If user has chosen disabled or older person; show hint that they only need to buy a ticket to travel before 9.30am

#### Train
- [x] User understands what rail zones mean
- [x] User can choose which rail zones they need to travel
- [x] User can find out which rail zones they need (use #67)
- [x] User can choose to see rail zones on a map (use #67)
- [x] User can choose to see a list of rail zones (use #67)
- [x] User can see a hint about choosing more rail zones if they regularly travel to another zone (use #67)
- [x] User can choose an out-of-county train station
- [x] User can choose if their ticket allows first-class travel

#### Bus
- [x] If user is just using bus mode; user understands what bus areas mean
- [x] If user is just using bus mode; user can choose which bus area their ticket covers
- [x] If user is just using bus mode; user can find out which bus area they need (use #68)
- [x] If user is just using bus mode; user can choose if they want a duration-based ticket; or a certain number of days travel ticket

#### Duration
- [x] User can see all possible durations of a ticket
- [x] User can see the cost of all durations
- [x] If user has chosen a certain number of days travel ticket (nBus); show bundles of tickets instead of duration
- [x] User can see the cost savings compared to buying the smallest ticket all the time
- [x] User can see the lowest price of a duration (example: if online sales are discounted by £5; but other channels have no discount; the lowest price should show)
- [x] User can see if a duration is discounted
- [x] User can choose a duration to continue to the summary page

#### Technical
- [x] As the user chooses each filter, refine ticket results to reveal the next filter
- [ ] If a user has previously used a microjourney (#67 or #68) **on that day** to find out which bus area or train zones they need, set this parameter on the page

***

**Comment by daylesalmon** [comment]
Awaiting test and potential minor design change(s) based on test results. 
Then re-assign to backlog/frontend.
